### ISSUE TITLE
if "embedded things go to dev-embedded"...

### ISSUE THREAD

**Issue by sarnold** [nxmyoz/c2-overlay#1]
then you need to update the DEPENDS in u-boot ebuilds because they still point to sys-boot.

Thanks.

**Comment by nxmyoz** [comment]
@sarnold: Thank you very much for pointing this out. It is very much appreciated.

https://github.com/nxmyoz/c2-overlay/commit/7fa4f6ed2ec785e66c104458cb237d6afd58d74c fixes that.
