### ISSUE TITLE
u-boot compilation

### ISSUE THREAD

**Issue by bjacquot** [nxmyoz/c2-overlay#2]
Hi,
it could be great to indicate that u-boot won't compile with a big value for MAKEOPTS="-jxx".
i encoutered this problem with -j10 (for distcc) wich result in an error :
make[2]: *** No rule to make target 'arch/arm/lib/crt0_aarch64_efi.o', needed by 'lib/efi_loader/helloworld.so'.  Stop.

no probem with -j1.

thanks.

**Comment by nxmyoz** [comment]
Hi,

thanks for reporting this.

I think I can set the MAKEOPTS in the ebuild. A safe value would be just -j1. Here it works with -j3 and -j4.

**Comment by bjacquot** [comment]
i haven't try with others values than 1 and 10.
perhaps just an info message which display when the emerge of the package start could be enough.

**Comment by nxmyoz** [comment]
I've added a message to reflect this issue.
